import { useQuery } from "@tanstack/react-query";
import { Download, FileText, Lock, MonitorDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getAuthToken } from "@/lib/api";
const headers = () => ({ Authorization: `Bearer ${getAuthToken()}` });
export default function Downloads() {
  const { data: config } = useQuery({ queryKey: ["/api/downloads/config"], queryFn: async () => { const r = await fetch("/api/downloads/config", { headers: headers() }); if (!r.ok) throw new Error("Download configuration is unavailable"); return r.json(); } });
  const allowed = config?.downloadEnabled === true;
  const download = async (type: string, url?: string) => { if (!allowed || !url) return; const r = await fetch("/api/downloads/log", { method: "POST", headers: { ...headers(), "Content-Type": "application/json" }, body: JSON.stringify({ file_type: type }) }); if (!r.ok) throw new Error("Unable to record download"); window.location.assign(url); };
  const cards = [{ type: "desktop_app", title: "GraderInsight Desktop App", meta: `Version ${config?.desktopApp?.version || "4.0"} · Windows · Local grading`, description: "The batch grading engine. Import assignments from your LMS, grade with AI, and export detailed feedback — all on your computer.", icon: MonitorDown, button: "Download for Windows", url: config?.files?.desktop_app?.url, requirements: "Windows 10 or later · Anthropic API key required" }, { type: "csv_viewer", title: "CSV Report Viewer", meta: "Browser-based tool · No installation needed", description: "View and navigate exported grading reports. Open the HTML file in Chrome and drag in your CSV export.", icon: FileText, button: "Download CSV Viewer", url: config?.files?.csv_viewer?.url }, { type: "quick_start_guide", title: "Quick Start Guide", meta: "PDF · Step-by-step setup instructions", description: "A practical guide for setting up and running your first grading batch.", icon: FileText, button: "Download Guide", url: config?.files?.quick_start_guide?.url }];
  return <div className="max-w-4xl mx-auto space-y-6"><div><h1 className="text-3xl font-bold">Downloads</h1><p className="text-muted-foreground">Everything you need to start grading on your own computer.</p></div>{!allowed && <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><Lock className="inline w-4 h-4 mr-2" />An active subscription is required to download. Upgrade in Settings to restore access.</div>}<div className="space-y-5">{cards.map(card => <Card key={card.type}><CardHeader><CardTitle className="flex gap-2 items-center"><card.icon className="w-5 h-5 text-primary" />{card.title}</CardTitle><CardDescription>{card.meta}</CardDescription></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">{card.description}</p><Button disabled={!allowed || !card.url} variant={card.type === "desktop_app" ? "default" : "outline"} onClick={() => download(card.type, card.url)}>{allowed ? <><Download className="w-4 h-4 mr-2" />{card.button}</> : "Upgrade to download"}</Button>{card.requirements && <p className="text-xs text-muted-foreground">System requirements: {card.requirements}</p>}</CardContent></Card>)}</div></div>;
}